### PR TITLE
GNU/Linux Support

### PR DESCRIPTION
**Pull request by bcambl**
Address issue #1  
- Add separate MAC and IP regex routines for posix

### CODE REVIEW

**Comment by ericdorsey** [comment]
What flavor *nix did you run this in? When I run (Ubuntu or Elementary [Freya]) this, I get:

```
$ python hostmac.py
Traceback (most recent call last):
  File "hostmac.py", line 168, in <module>
    myIP = ([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")][0])
IndexError: list index out of range
```

Love the idea of making this *nix compliant, but thinking we need to use something like `netifaces` for a more robust check of network interfaces / ways to detect IP.

**Comment by bcambl** [comment]
I mostly develop for Fedora/CentOS/RHEL.
I have added another commit to this branch to address your comment error.
I re-wrote the ip detection function and seems to test OK in the following environments:
- Fedora 21 (python 2.7.8)
- CentOS 6.6 (python 2.6.6)
- CentoOS 7.0 (python 2.7.5)
- Ubuntu 14.10 (2.7.8)
- Windows 8 (python 2.7.9)
- Windows 8 + Cygwin (python 2.7.8)

I did not test Elementary although it should be the same as Ubuntu.. Let me know if this is now working for you. Yes, we could use a pypi package to make things a bit easier, but it is always nice to stick with standard libraries if possible :)

**Comment by ericdorsey** [comment]
Merged.

Cool that this is still using the standard library. Care to explain these two lines?

170: `s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)`
172: `s.connect(('example.com', 0))`

Does this actually try to establish a new socket to example.com?

**Comment by bcambl** [comment]
170: `s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)`
The above line is creating a new socket. I am passing in an 'address family' of `AF_INET` which is the internet IPv4 address family. The socket type is `SOCK_DGRAM` or better known as UDP (User Datagram Protocol). I am using UDP because I only care about building a connection and not the response.

172: `s.connect(('example.com', 0))`
If we did not call the above line: 
`s.getsockname()` would return `('0.0.0.0', 0)`
But, if we tell it to connect (even if it is an invalid request):
`s.getsockname()` populates with: `('<your_ip>', <random_port>)`
In all honesty, instead of example.com, I could have used `254.254.254.254` and it still works. 
Since all we care about is building the connection to utilize `s.getsockname()` to find our IP, we can use any routable IP in place of example.com.

**Comment by ericdorsey** [comment]
Awesome! Thanks for the walkthrough of how you pulled the IP out. Nice!

**Pull request merged**
