### PR TITLE
add subproc_pipe_runner() function to avoid shell=True

### PR DESCRIPTION
**Pull request by ericdorsey**

### CODE REVIEW

**Comment by ericdorsey** [comment]
Opening this a "needs testing & conversation" PR 
Ref #50
- Added a `subproc_pipe_runner()` that dynamically builds `subprocess.Popen` commands (either one or two processes, accommodating whether the command needs to be piped or not)
  - function tries to prevent lots of individual custom `subprocess.Popen` lines for each command, and instead abstracts it out
- smbutil would need it's own "os specific" command string in `detect_os()` as that call is kind of chasing it's own tail with this
- lots of ugly debug and old code in there currently 

Have only tested it on OSX so far. 

Modeled off this 
http://stackoverflow.com/a/6780118

**Comment by ericdorsey** [comment]
Tests good:
- Win 7: py 2.7.2 and 3.4.3

**Comment by bcambl** [comment]
Works on Linux.

**Comment by ericdorsey** [comment]
Tests good Ubuntu 14.04.2, Python 2.7.6

**Comment by ericdorsey** [comment]
Going to clean up the code before pulling this in.

**Pull request merged**
