### PR TITLE
Allow manual IP entry when unable to detect

### PR DESCRIPTION
**Pull request by bcambl**
Address Issues #9 & #10
- Allow for manual ip entry when detect_ip function fails
- Changed socket.connect from `example.com` to something more ambiguous.

### CODE REVIEW

**Comment by ericdorsey** [comment]
Looks like my Windows 7 box can't route to `255.255.255.254`, immediately falls to the except block (I've exposed the error here with `except socket.error as err:`)

```
C:\HostMAC>python hostmac.py
[Errno 10051] A socket operation was attempted to an unreachable network
Failed to detect IP of current host!
```

Windows sockets error codes, values, and meanings
https://support.microsoft.com/en-us/kb/819124

```
WSAENETUNREACH (10051)

Translation: Network is unreachable.
Description: A socket operation is tried to an unreachable network. This error typically means the local software knows no route to reach the remote host.
```

These all work:

```
s.connect(('1.1.1.1', 0))
s.connect(('192.192.192.192', 0))
s.connect(('foo.com', 0))
s.connect(('1.2.3.4', 0))
```

Helpful..?
http://stackoverflow.com/questions/11717393/a-socket-operation-was-attempted-to-an-unreachable-network-in-python-httplib

Haven't tried it on OSX Or Ubuntu yet. 

What's "better".. `example.com` or `1.1.1.1` or..? :)

**Comment by ericdorsey** [comment]
Runs just fine in Ubuntu.

For OSX, I think this is currently expected / working as the code is, in that it dumps right to "failed to detect":

```
$ python hostmac.py
Failed to detect IP of current host!
(I)nput IP manually, or (Q)uit:q'
Quitting..
```

But, for OSX, we have to adjust the `arp` request it looks like. Works a bit diff than Ubuntu:

```
# OSX 

~ $ arp -a 192.168.1.1
usage: arp [-n] [-i interface] hostname
       arp [-n] [-i interface] [-l] -a
       arp -d hostname [pub] [ifscope interface]
       arp -d [-i interface] -a
       arp -s hostname ether_addr [temp] [reject] [blackhole] [pub [only]] [ifscope interface]
       arp -S hostname ether_addr [temp] [reject] [blackhole] [pub [only]] [ifscope interface]
       arp -f filename
```

We can get it with 

```
# also OSX 

~ $ arp -a | grep 192.168.1.1
? (192.168.1.1) at ff:ee:ff:aa:00:00 on en0 ifscope [ethernet]
```

But Ubuntu returns a bunch of matches with that:

```
# Ubuntu 

$ arp -a | grep 192.168.1.1
? (192.168.1.12) at <incomplete> on eth0
? (192.168.1.1) at ff:ee:ff:aa:00:00 [ether] on eth0
? (192.168.1.15) at <incomplete> on eth0
? (192.168.1.14) at <incomplete> on eth0
```

But I think this will work on both OSX and *nix

```
# returns just one line on Ubuntu and OSX

$ arp -a | grep -w 192.168.1.1
```

So thinking we want to update `getMac()` to use `arp -a | grep -w {current IP}` for *nix / posix.

**Comment by bcambl** [comment]
I like: `1.1.1.1` or `1.2.3.4`
What do you like better?
I will update the PR.

**Comment by ericdorsey** [comment]
I think either `1.1.1.1` or `1.2.3.4` are pretty obvious "this isn't a real IP" IP's.. I'm good with either!

**Comment by ericdorsey** [comment]
Only someone digging into the code to see how the IP was pulled out will care, but I like that it's a pretty obviously fake address. We could note in there that there isn't an actual network call to that IP & socket.

**Comment by bcambl** [comment]
PR updated and added a docstring to the ip detection function.

**Comment by ericdorsey** [comment]
Awesome, thank you!

**Pull request merged**
